# Generated by Django 2.0 on 2020-01-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_message_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
