# Generated by Django 2.0 on 2020-01-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
